#pragma once

namespace Client
{
	enum ANITYPE
	{
		ANI_STOP
		, ANI_LOOP
		, ANI_BACKTOIDLE
		, ANI_CHAIN
		, ANI_BACKTOANOTHER

		, ANI_END
	};

	enum OBJ_STATE // b 붙어있는건 뒷걸음질치면서 하는 모션
	{
		OBJSTATE_IDLE
		, OBJSTATE_ATT1
		, OBJSTATE_ATT1_B
		, OBJSTATE_ATT2
		, OBJSTATE_ATT2_B
		, OBJSTATE_ATT3
		, OBJSTATE_ATT3_B
		, OBJSTATE_ATT4
		, OBJSTATE_ATT4_B
		, OBJSTATE_ATT5
		, OBJSTATE_ATT6
		, OBJSTATE_ATT7
		, OBJSTATE_ATT8
		, OBJSTATE_ATT9

		, OBJSTATE_THROWSHILD
		, OBJSTATE_THROWSHILD_B

		, OBJSTATE_STOP

		, OBJSTATE_RUSH
		, OBJSTATE_BLOCK
		, OBJSTATE_BLOCKIDLE
		, OBJSTATE_BLOCKSTART
		, OBJSTATE_BLOCKWALK_B
		, OBJSTATE_BLOCKWALK_F
		, OBJSTATE_BLOCKWALK_RF
		, OBJSTATE_BLOCKWALK_RB
		, OBJSTATE_BLOCKWALK_LF
		, OBJSTATE_BLOCKWALK_LB
		, OBJSTATE_BLOCKATT
		, OBJSTATE_BLOCKIDLE_DAMAGED
		, OBJSTATE_BLOCKEND

		, OBJSTATE_BACKROLL
		, OBJSTATE_CHANGECB // 전투준비
		, OBJSTATE_CHANGECB_B
		, OBJSTATE_CHANGECO //전투해제
		, OBJSTATE_CHANGECO_B
		, OBJSTATE_ANGER
		, OBJSTATE_BIGSTEP
		, OBJSTATE_OVERPOWER
		, OBJSTATE_OVERPOWER_B
		, OBJSTATE_FLYSMASH
		, OBJSTATE_LANDRUN
		, OBJSTATE_LANDSTAND
		, OBJSTATE_ROLL
		, OBJSTATE_RIDEROLL
		, OBJSTATE_ROTATEL180
		, OBJSTATE_ROTATEL90
		, OBJSTATE_ROTATER180
		, OBJSTATE_ROTATER90
		, OBJSTATE_RUNSTARTF
		, OBJSTATE_RUNSTARTL
		, OBJSTATE_RUNSTARTR
		, OBJSTATE_RUN_B
		, OBJSTATE_RUN
		, OBJSTATE_RUN_L
		, OBJSTATE_RUN_LB
		, OBJSTATE_RUN_R
		, OBJSTATE_RUN_RB









		, OBJSTATE_END
	};

	enum KeyType
	{
		ESC = 0x01
		, Key1 = 0x02
		, Key2 = 0x03
		, Key3 = 0x04
		, Key4 = 0x05
		, Key5 = 0x06
		, Key6 = 0x07
		, Key7 = 0x08
		, Key8 = 0x09
		, Key9 = 0x0A
		, Key0 = 0x0B
		, BACKSPACE = 0x0E
		, TAB = 0x0F
		, Q = 0x10
		, W = 0x11
		, E = 0x12
		, R = 0x13
		, T = 0x14
		, Y = 0x15
		, U = 0x16
		, I = 0x17
		, O = 0x18
		, P = 0x19
		, ENTER = 0x1C
		, LCTRL = 0x1D
		, A = 0x1E
		, S = 0x1F
		, D = 0x20
		, F = 0x21
		, G = 0x22
		, LSHIFT = 0x2A
		, Z = 0x2C
		, X = 0x2D
		, C = 0x2E
		, V = 0x2F
		, SPACE = 0x39
		, F1 = 0x3B
		, F2 = 0x3C
		, F3 = 0x3D
		, F4 = 0x3E
		, F5 = 0x3F
		, UP = 0xC8
		, LEFT = 0xCB
		, RIGHT = 0xCD
		, DOWN = 0xD0

		, Key_End
	};
}